### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by xhaross** [Shoutzor/Shoutzor#46]
need solution for login

![er](https://user-images.githubusercontent.com/68476431/140680758-4ad02f13-8e57-4ac7-b116-5f147532a405.png)

**Comment by xorinzor** [comment]
Can you provide more details?

If you know how, can you check the Web Console and tell me what the exact server response is to the "/login" request?
Additionally, is there anything in the laravel log file? (located at /storage/logs)

Finally, be aware that shoutzor is currently still under development and lacks any actual functionality in it's current state. I hope to continue the project soon, but personal life is messing things up currently.

**Comment by xorinzor** [comment]
Due to the lack of details I cannot resolve this issue. If you provide them later on I will re-open the issue. For now I'll close it.
